[package]
authors = ["Matthew Collins"]
build = "build.rs"
name = "gl33"
version = "0.0.1"
license = "GPL-3.0-or-later"

[build-dependencies]
gl_generator = "0.14.0"
khronos_api = "3.1.0"

[dependencies]
libc = "0.2.65"
