[package]
authors = ["Matthew Collins"]
build = "build.rs"
name = "lua-sys"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"

[build-dependencies]
cc = "1.0.47"
glob = "0.3.0"

[dependencies]
libc = "0.2.65"
